In [2]:
import numpy as np

In [2]:
l1 = [1,2,3,4]

In [3]:
np.array(l1)

array([1, 2, 3, 4])

In [5]:
n1 = np.array(l1)

In [6]:
n1

array([1, 2, 3, 4])

In [7]:
type(n1)

numpy.ndarray

In [3]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [4]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

# Initializing Numpy Array

# Initializing NumPy array with zero

In [7]:
n3 = np.zeros((2,3))

In [8]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
n3 = np.zeros((10,10))

In [10]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Initializing NumPy array with same number

In [13]:
n1= np.full((2,10),10)
n1

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

# Initializing NumPy array within a range

In [15]:
n1 = np.arange(50,101)


In [16]:
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
n1 = np.arange(50,500,10)
n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

# Initializing NumPy array with random numbers

In [20]:
import numpy as np

In [28]:
np.random.randint(1,100,5)


array([89, 86, 38, 46, 60])

# Checking the shape of NumPy arrays

In [29]:
n1 = np.array([[1,2,3,4],[4,3,2,1]])

In [30]:
n1

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [32]:
n1.shape

(2, 4)

In [34]:
n1.shape=(4,2)

In [35]:
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [37]:
n1.shape = (1,8)

In [38]:
n1

array([[1, 2, 3, 4, 4, 3, 2, 1]])

# joining NumPy Arrays

# vstack

In [40]:
n1 = np.array([1,2,3])

In [41]:
n2 = np.array([4,5,6])

In [44]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

# hstack


In [45]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

# column_stack

In [47]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy Intersection & Difference

In [48]:
import numpy as np

In [52]:
n1 = np.array([10,20,30,40,50,60])

In [53]:
n2 = np.array([50,60,70,80,90])

In [54]:
np.intersect1d(n1,n2)

array([50, 60])

In [55]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [57]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# Addition of NumPy arrays

In [58]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [59]:
np.sum([n1,n2])

100

In [60]:
np.sum([n1,n2],axis = 0)

array([40, 60])

In [61]:
np.sum([n1,n2],axis = 1)

array([30, 70])

# NumPy Array Mathematics

In [62]:
n1 = np.array([10,20,30])
n1

array([10, 20, 30])

In [63]:
n1+5

array([15, 25, 35])

In [64]:
n1-5

array([ 5, 15, 25])

In [65]:
n1*10

array([100, 200, 300])

In [68]:
n1/5

array([2., 4., 6.])

# NumPy Math Functions

In [69]:
n1 = np.random.randint(1,50,10)

In [70]:
n1

array([11,  9, 47, 29,  6, 31,  5, 46, 12, 25])

In [71]:
np.mean(n1)

22.1

In [72]:
np.median(n1)

18.5

In [73]:
np.std(n1)

15.082771628583389

 # NumPy Save & Load

In [76]:
n1 = np.array([10,20,30,40,50])

In [77]:
np.save('myarray',n1)

In [78]:
new_n1 = np.load('myarray.npy')

In [79]:
new_n1

array([10, 20, 30, 40, 50])